[build]
  publish = "build"
  command = "node build"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301

# [[redirects]]
#   from = "/en"
#   to = "/"
#   status = 301

# [[redirects]]
#   from = "/en/*"
#   to = "/"
#   status = 301
