[build]
  publish = "build"
  command = "node build"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301

[[redirects]]
  from = "/[^en|fr|pt-br|zh-hans|zh-hant|ru]/*"
  to = "/en/"
  status = 301

