[build]
  publish = "build"
  command = "node build"

[[redirects]]
  from = "/*"  
  to = "/fr/:splat"
  status = 302  
  conditions = {Country = ["FR"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 301

